services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # 👈 Mount local code to container
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - ./backend/.env


  frontend:
    build: ./frontend
    ports:
      - "3000:80" # or 5173 if you're using vite preview
    volumes:
      - ./frontend:/app  # 👈 Mount local code to container