services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=your-key-here

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # or 5173 if you're using vite preview
