version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=your-key-here
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
